### PR TITLE
Clean up unused

### PR DESCRIPTION
**Pull request by jennydaman**

### CODE REVIEW

**Comment by mairin** [comment]
Why delete the video poster attribute? (That was added for mobile firefox compat IIRC)

**Comment by jennydaman** [comment]
We don't have a poster.png, should we add one?

**Comment by mairin** [comment]
Oh! let me look

**Comment by mairin** [comment]
(I thought it was the attribute on the tag... that tag is full of magical incantations, i thought one was "poster")

**Comment by mairin** [comment]
OK apparently not because if it's not there, the jumbo isn't broken (it doesn't play but it is displaying a solid image) on firefox mobile so I will just merge this :)

**Pull request merged**
